<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<div class="block block-customer-login db">
    <div style="text-align: center" class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('SING IN')) ?></strong>
    </div>
    <div style="margin: auto" class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login form-login-user"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset  class="fieldset login" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                <div class="field note"><?= $block->escapeHtml(__('')) ?></div>
                <div class="field email required">
                    <label style="text-align: left !important" class="label" for="email"><span><?= $block->escapeHtml(__('Email Address')) ?></span></label>
                    <div class="control">
                        <input class="input-page" name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <label style="text-align: left !important" for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control" style="position: relative;box-sizing: border-box;">
                        <input class="input-page" name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                            <button type="button" class="hide-show" aria-label="Show Password">
                            <span class="show">SHOW</span>
                            </button>
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
              
                <div style="text-align: center" class="actions-toolbar">
                    <div class="secondary"><a class="action remind" style="color: #666666" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Password?')) ?></span></a></div>
                </div>
                <div  style="text-align: center"  class="actions-toolbar">
                    <div class="primary"><center><button type="submit" class="action login primary" name="send" id="send2" style="width: 114px;border-radius: 0px;background: #333;
    border: #333;"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button></center></div>
                </div>
                <div style="text-align: center" >
                    <span><a style="color: #666666;" class="subrayado-simple" href="#">Privacy Policy</a></span>
                </div>
               
            </fieldset>
        </form>
        
    </div>
</div>
<script type="text/javascript">
            require(['jquery'],function($){
                console.log('hola');
                $(document).ready(function() {
                    $('#btnchang').on('click',function(){
                        const inputElm = $('#passchang');
                        const showElm = $('.show');

                        if(inputElm.attr('type') == "password") {
                            
                            showElm.text("HIDE");
                            inputElm.attr("type","text");
                            
                        }else {
                            showElm.text("SHOW");
                            inputElm.attr("type","password");
                        }
                       
                    });
                });
            });    
        </script>