// es el bloque
<ul class="ul-list">
                    <li class="new-row">
                        <a href="<?php echo $block->getUrl('') ?>">
                            <img src="/media/porto/page_bg/Citrus.jpg" alt="Citrus">
                        </a>
                    </li>
                    <li class="new-row">
                        <a href="<?php echo $block->getUrl('') ?>">
                            <img src="/media/porto/page_bg/Exotic.jpg" alt="Citrus">
                        </a>
                    </li>
                    <li class="new-row">
                        <a href="<?php echo $block->getUrl('') ?>">
                            <img src="/media/porto/page_bg/Floral.jpg" alt="Citrus">
                        </a>
                    </li>
                    <li class="new-row">
                        <a href="<?php echo $block->getUrl('') ?>">
                            <img src="/media/porto/page_bg/Fresh.jpg" alt="Citrus">
                        </a>
                    </li>
                    <li class="new-row">
                        <a href="<?php echo $block->getUrl('') ?>">
                            <img src="/media/porto/page_bg/Fruit.jpg" alt="Citrus">
                        </a>
                    </li>
                    <li class="new-row">
                        <a href="<?php echo $block->getUrl('') ?>">
                            <img src="/media/porto/page_bg/Gourmand.jpg" alt="Citrus">
                        </a>
                    </li>
                    <li class="new-row"> 
                            <a href="<?php echo $block->getUrl('') ?>">
                                    <img src="/media/porto/page_bg/Warm.jpg"  alt="Citrus">
                                </a>
                    </li>
                    <li class="new-row">
                            <a href="<?php echo $block->getUrl('') ?>">
                                    <img src="/media/porto/page_bg/Woods.jpg" alt="Citrus">
                            </a>
                    </li>
        </ul>

// para cms

        <ul class="ul-list clearfix">
                    <li class="new-row">
                        <a href="<?php echo $block->getUrl('') ?>">
                            <img src="{{media url=&quot;porto/page_bg/Citrus.jpg.jpg&quot;}}" alt="Citrus">
                        </a>
                    </li>
                    <li class="new-row">
                        <a href="<?php echo $block->getUrl('politicas-de-privacidad') ?>">
                            <img src="{{media url=&quot;porto/page_bg/Exotic.jpg&quot;}}" alt="Citrus">
                        </a>
                    </li>
                    <li class="new-row">
                        <a href="<?php echo $block->getUrl('politicas-de-privacidad') ?>">
                            <img src="{{media url=&quot;porto/page_bg/Floral.jpg&quot;}}" alt="Citrus">
                        </a>
                    </li>
                    <li class="new-row">
                        <a href="<?php echo $block->getUrl('politicas-de-privacidad') ?>">
                            <img src="{{media url=&quot;porto/page_bg/Fresh.jpg&quot;}}" alt="Citrus">
                        </a>
                    </li>
                    <li class="new-row">
                        <a href="<?php echo $block->getUrl('politicas-de-privacidad') ?>">
                            <img src="{{media url=&quot;porto/page_bg/Fruit.jpg&quot;}}" alt="Citrus">
                        </a>
                    </li>
                    <li class="new-row">
                        <a href="<?php echo $block->getUrl('politicas-de-privacidad') ?>">
                        <img src="{{media url=&quot;porto/page_bg/Gourmand.jpg&quot;}}" alt="Citrus">
                        </a>
                    </li>
                    <li class="new-row"> 
                            <a href="<?php echo $block->getUrl('politicas-de-privacidad') ?>">
                                    <img src="{{media url=&quot;porto/page_bg/Warm.jpg&quot;}}"  alt="Citrus">
                                </a>
                    </li>
                    <li class="new-row">
                            <a href="<?php echo $block->getUrl('politicas-de-privacidad') ?>">
                                    <img src="{{media url=&quot;porto/page_bg/Woods.jpg&quot;}}" alt="Citrus">
                            </a>
                    </li>
                </ul>