<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>404</title>
</head>
<body>
<div class="null-search-content">
        <div class="wrap-search">
            <h1><?= $block->escapeHtml(__('No Results Found')) ?></h1>
            <div class="section-header">
                <span>
                <?= $block->escapeHtml(__('We couldn’t find anything for')) ?></span>
                <span>""</span>   
            </div>
        </div>
        <div class="promo-block">
                <h2 class="title">
                        <span><?= $block->escapeHtml(__('YOU MAY ALSO LIKE')) ?></span>   
                </h2>
        </div>
        <div class="promo-block">
                <h2 class="title">
                        <span><?= $block->escapeHtml(__('CUSTOMER FAVES')) ?></span>   
                </h2>
        </div>
        <div class="home-bottom-slots">
                <div style="padding-top: 20px;">
                        <div class="">
                            <h2 class="filterproduct-title">
                                <strong><?= $block->escapeHtml(__('SHOP BY CATEGORY BLOCK')) ?></strong>
                             </h2>
                            <div class="cont-cate grid-container text-center">
                                <div class="item-cat">
                                    <img src="/media/porto/home_cat1.png" class="rounded cat-img"
                                        alt="">
                                    <p class="title-cat"><?= $block->escapeHtml(__('Cuidado Corporal')) ?></p>
                                    <span class="text-cat">
                                    <?= $block->escapeHtml(__('Bath and Body Works is your go-to
                                        place for gifts & goodies.')) ?>
                                    </span>
                                    <a href="<?php $block->getUrl('cuidado-corporal.html')?>" class="btn-cat">
                                    <?= $block->escapeHtml(__('SHOP NOW')) ?>
                                    </a>
                                </div>
                                <div class="item-cat">
                                    <img src="/media/porto/home_cat2.png" class="rounded cat-img"
                                        alt="">
                                    <p class="title-cat"><?= $block->escapeHtml(__('Hogar')) ?></p>
                                    <span class="text-cat">
                                    <?= $block->escapeHtml(__('Bath and Body Works is your go-to
                                        place for gifts & goodies.')) ?>
                                    </span>
                                    <a href="<?php $block->getUrl('hogar.html')?>" class="btn-cat">
                                    <?= $block->escapeHtml(__('SHOP NOW')) ?>
                                    </a>
                                </div>
                                <div class="item-cat">
                                    <img src="/media/porto/home_cat3.png" class="rounded cat-img"
                                        alt="">
                                    <p class="title-cat"><?= $block->escapeHtml(__('HOGAR')) ?></p>
                                    <span class="text-cat">
                                    <?= $block->escapeHtml(__('Bath and Body Works is your go-to
                                        place for gifts & goodies.')) ?>
                                    </span>
                                    <a href="<?php $block->getUrl('hogar/velas/velas-3-mechas.html')?>" class="btn-cat">
                                    <?= $block->escapeHtml(__('SHOP NOW')) ?>
                                    </a>
                                </div>
                                <div class="item-cat">
                                    <img src="/media/porto/home_cat4.png" class="rounded cat-img"
                                        alt="">
                                    <p class="title-cat"><?= $block->escapeHtml(__('Jabones')) ?></p>
                                    <span class="text-cat">
                                    <?= $block->escapeHtml(__('Bath and Body Works is your go-to
                                        place for gifts & goodies.')) ?>
                                    </span>
                                    <a href="<?php $block->getUrl('jabones.html')?>" class="btn-cat">
                                    <?= $block->escapeHtml(__('SHOP NOW')) ?>
                                    </a>
                                </div>
                                <div class="item-cat">
                                    <img src="/media/porto/home_cat5.png" class="rounded cat-img"
                                        alt="">
                                    <p class="title-cat"><?= $block->escapeHtml(__('Cuidado Corporal')) ?></p>
                                    <span class="text-cat">
                                    <?= $block->escapeHtml(__('Bath and Body Works is your go-to
                                        place for gifts & goodies.')) ?>
                                    </span>
                                    <a href="<?php $block->getUrl('cuidado-corporal/ba-o-y-ducha/jabon-liquido-y-gel-de-ba-o.html')?>" class="btn-cat">
                                    <?= $block->escapeHtml(__('SHOP NOW')) ?>
                                    </a>
                                </div>
                                <div class="item-cat">
                                    <img src="/media/porto/home_cat6.png&quot;}}" class="rounded cat-img"
                                        alt="">
                                    <p class="title-cat"><?= $block->escapeHtml(__('Regalos')) ?></p>
                                    <span class="text-cat">
                                    <?= $block->escapeHtml(__('Bath and Body Works is your go-to
                                        place for gifts & goodies.')) ?>
                                    </span>
                                    <a href="<?php $block->getUrl('regalos.html')?>" class="btn-cat">
                                    <?= $block->escapeHtml(__('SHOP NOW')) ?>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
            
            <div class="home-grid-one responsive-grid">
                    <div class="grid-col">
                        <div class="nullsearch-utility-links">
                            <div class="content-asset">
                                <div class="ns-utility-links under-menu clearfix">
                                                        <h2>
                                                            <span><?= $block->escapeHtml(__('More Ways to Shop')) ?></span>
                                                        </h2>
                                                        <ul class="clearfix">
                                                            <li class="first odd">
                                                                <a href="<?php $block->getUrl('regalos.html')?>" manual_cm_re="Null_search-_-hs1-_-Gift_cards">
                                                                    <img alt="Gift Cards" src="/media/porto/page_bg/gift-cards.svg">
                                                                    <span><?= $block->escapeHtml(__('Gift Cards')) ?></span>
                                                                </a>
                                                            </li>
                                                            <li class="even">
                                                                <a href="<?php $block->getUrl('cuidado-corporal.html')?>" manual_cm_re="Null_search-_-hs2-_-Find_a_fragrance">
                                                                    <img alt="Find a Fragrance" src="/media/porto/page_bg/find-a-fragrance.svg">
                                                                    <span><?= $block->escapeHtml(__('Find a Fragrance')) ?></span>
                                                                </a>
                                                            </li>
                                                            <li class="odd even">
                                                                <a href="<?php $block->getUrl('store-locator/')?>" manual_cm_re="Null_search-_-hs3-_-Find_a_store">
                                                                    <img alt="Find a Store" src="/media/porto/page_bg/find-a-store.svg">
                                                                    <span><?= $block->escapeHtml(__('Find a Store')) ?></span>
                                                                </a>
                                                            </li>
                                                        </ul>
                                                    </div>
                                </div>
                        </div>
                    </div>
                </div>
        </div>
        
       
    </div>

</body>
</html>